### ISSUE TITLE
cannot open include file msvc_compat.h

### ISSUE THREAD

**Issue by johnjohnsp1** [season-lab/bluepill#4]
hello, thanks for sharing the code, was giving a try but getting this error:
Error	C1083	Cannot open include file: 'include/msvc_compat.h': No such file or directory	bluepill	c:\temp\bluepill\pintool\src\libdft\bridge.cpp	1	

anything i do wrong ? using
Microsoft Visual Studio Community 2017 
Version 15.9.21
VisualStudio.15.Release/15.9.21+28307.1064
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA838
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.61435.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.9.03024.0
Azure Functions and Web Jobs Tools

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.9.18254.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Debugging Tools for Windows   10.0.17740.1000
Integrates the Windows Debugger functionality (http://go.microsoft.com/fwlink/?linkid=223405) in Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.20417.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

MonoTools.Debugger   2.0
MonoTools.Debugger

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.9.18254.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.9.18254.1
Provides templates and integration for the Django web framework.

Python - IronPython support   15.9.18254.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.9.18254.1
Profiling support for Python projects.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.62002.01090
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.9.30718.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.1062
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Windows Driver Kit   10.0.17740.1000
Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)

WiX Toolset Visual Studio Extension   1.0.0.4
WiX Toolset Visual Studio Extension version 1.0.0.4
Copyright (c) .NET Foundation and contributors. All rights reserved.

even with 2019 getting the same error but also i dont see the folder include mentioned
thanks

**Comment by dcdelia** [comment]
Hi, thank you for your interest in BluePill!

Where is Pin installed and which version are you using? Something may be wrong with the include paths.

`msvc_compat.h` is located in `C:\<Pin folder>\extras\crt\include`. You can set the Pin folder (default is `C:\Pin311`) from the *Property Manager* pane of Visual Studio or more simply by editing the `<PinFolder>C:\Pin311</PinFolder>` line in `Locals.props` in the project folder.

I will give it a try myself with Visual Studio 2017 and see if it's some other issue instead. We have used VS2015 so far but we no longer need version-specific features, so VS2017 will soon become the default.

**Comment by johnjohnsp1** [comment]
actually i have as target bluepill project with sdk 10.0.18362.0 but also trying a lower sdk as 10.0.17763.0 the error is the same keep saying msv_compat.h missing
thanks

**Comment by dcdelia** [comment]
I just updated the documentation and the VS project file after some testing under Visual Studio 2017 and the 10.0.17763.0 SDK. Now they work fine on my end! Check these lines in your `Locals.props` file:
```
  <PropertyGroup Label="UserMacros">
    <PinFolder>C:\Pin311</PinFolder>
    <WinHPath>C:/Program Files (x86)/Windows Kits/8.1/Include/um</WinHPath>
  </PropertyGroup>
```
When you download Pin and extract it, Visual Studio should be able to find `msvc_compat.h` under `$(PinFolder)\extras\crt\include`. Also change `WinHPath` to point to the right SDK directory (e.g. `C:/Program Files/Windows Kits/10/Include/10.0.17763.0/um`) containing `Windows.h`.

**Comment by johnjohnsp1** [comment]
Thanks for taking a fix, did it a try now:

1>------ Build started: Project: bluepill, Configuration: Debug Win32 ------
1>itree.cpp
1>exceptionHandler.cpp
1>functions.cpp
1>helper.cpp
1>HiddenElements.cpp
1>ins.cpp
1>main.cpp
1>bridge.cpp
1>context.cpp
1>fpu.cpp
1>syshooking.cpp
1>libdft_api.cpp
1>libdft_core.cpp
1>logging.cpp
1>memory.cpp
1>tagmap.cpp
1>tag_traits.cpp
1>process.cpp
1>state.cpp
1>syshooks.cpp
1>c:\temp\bluepill\pintool\src\syshooks.cpp(21): warning C4244: 'initializing': conversion from '__int64' to 'W::UINT', possible loss of data
1>c:\temp\bluepill\pintool\src\syshooks.cpp(467): warning C4244: 'initializing': conversion from '__int64' to 'W::UINT32', possible loss of data
1>Generating Code...
1>Compiling...
1>wmi.cpp
1>Generating Code...
1>   Creating library C:\Pin311\bluepill32.lib and object C:\Pin311\bluepill32.exp
1>pin.lib(pin_client.obj) : warning LNK4217: locally defined symbol ?cout@std@@3V?$basic_ostream@DV?$char_traits@D@std@@@1@A (class std::basic_ostream<char,class std::char_traits<char> > std::cout) imported in function "void __cdecl LEVEL_PINCLIENT::DumpPinVersion(void)" (?DumpPinVersion@LEVEL_PINCLIENT@@YAXXZ)
1>pintool.vcxproj -> C:\Pin311\bluepill32.dll
1>Done building project "pintool.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

suppose it worked good right ?
thanks once more

**Comment by dcdelia** [comment]
Yes, good to go :-) my pleasure!
